stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  script:
    - cargo build --verbose
    - cargo test --verbose
    - rustup component add clippy
    - cargo clippy -- -Dwarnings -Wclippy::pedantic
    - rustup component add rustfmt
    - cargo fmt -- --check

rust-nightly:
  stage: build
  image: rustlang/rust:nightly
  script:
    - cargo build --verbose
    - cargo test --verbose
  allow_failure: true
