image: rustlang/rust:nightly

run-tests-release:
  script:
    - cd core
    - rustc --version && cargo --version 
    - cargo test --release --verbose 

run-tests-debug:
  script:
    - cd core
    - rustc --version && cargo --version 
    - cargo test --verbose 

clippy:
  script:
    - rustup component add clippy
    - cd core
    - cargo clippy
    - cd ../bindings
    - cargo clippy

format-check:
  script:
    - rustup component add rustfmt
    - cd core
    - cargo fmt -- --check
    - cd ../bindings
    - cargo fmt -- --check
